
--- # 数据源配置
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    # 动态数据源文档 https://www.kancloud.cn/tracy5546/dynamic-datasource/content
    dynamic:
      # 性能分析插件(有性能损耗 不建议生产环境使用)
      p6spy: true
      # 设置默认的数据源或者数据源组,默认值即为 master
      primary: master
      # 严格模式 匹配不到数据源则报错
      strict: true
      datasource:
        # 主库数据源
        master:
          type: ${spring.datasource.type}
          driverClassName: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/ruoyi-ai?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&autoReconnect=true&rewriteBatchedStatements=true
          username: root
          password: root

      hikari:
        # 最大连接池数量
        maxPoolSize: 20
        # 最小空闲线程数量
        minIdle: 10
        # 配置获取连接等待超时的时间
        connectionTimeout: 30000
        # 校验超时时间
        validationTimeout: 5000
        # 空闲连接存活最大时间，默认10分钟
        idleTimeout: 600000
        # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认30分钟
        maxLifetime: 1800000
        # 连接测试query（配置检测连接是否有效）
        connectionTestQuery: SELECT 1
        # 多久检查一次连接的活性
        keepaliveTime: 30000

--- # redis 单机配置(单机与集群只能开启一个另一个需要注释掉)
spring.data:
  redis:
    # 地址
    host: 127.0.0.1
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 2
    # 密码(如没有密码请注释掉)
    # password: 123456
    # 连接超时时间
    timeout: 10S
redisson:
  # redis key前缀
  keyPrefix:
  # 线程池数量
  threads: 4
  # Netty线程池数量
  nettyThreads: 8
  # 单节点配置
  singleServerConfig:
    # 客户端名称
    clientName: ${ruoyi.name}
    # 最小空闲连接数
    connectionMinimumIdleSize: 8
    # 连接池大小
    connectionPoolSize: 32
    # 连接空闲超时，单位：毫秒
    idleConnectionTimeout: 10000
    # 命令等待超时，单位：毫秒
    timeout: 3000
    # 发布和订阅连接池大小
    subscriptionConnectionPoolSize: 50

--- # sms 短信
sms:
  enabled: false
  # 阿里云 dysmsapi.aliyuncs.com
  # 腾讯云 sms.tencentcloudapi.com
  endpoint: "dysmsapi.aliyuncs.com"
  accessKeyId: xxxxxxx
  accessKeySecret: xxxxxx
  signName: 测试
  # 腾讯专用
  sdkAppId:

pdf:
  extract:
    service:
      url: http://localhost:8080
    ai-api:
      url: https://api.pandarobot.chat/v1/chat/completions
      key: sk-xxxx
  transition:
    # 是否开启mineru
    enable-minerU: true
    # mineru conda环境路径
    conda-env-path: "F:\\ProgramData\\Computer\\Anaconda\\envs\\mineru"
    # 是否开启图片OCR
    enable-ocr: true
#百炼模型配置
dashscope:
  key: sk-xxxx
  model: qvq-max

--- # Neo4j 知识图谱配置
neo4j:
  uri: bolt://127.0.0.1:7687
  username: neo4j
  password: MySecurePass123!
  database: neo4j
  max-connection-pool-size: 50
  connection-timeout-seconds: 30

# 知识图谱配置
knowledge:
  graph:
    # 是否启用知识图谱功能
    enabled: true
    # 图数据库类型: neo4j 或 apache-age
    database-type: neo4j
    # 是否自动创建索引
    auto-create-index: true
    # 批量处理大小
    batch-size: 1000
    # 最大重试次数
    max-retry-count: 3

    # 实体抽取配置
    extraction:
      # 置信度阈值（低于此值的实体将被过滤）
      confidence-threshold: 0.7
      # 最大实体数量（每个文档）
      max-entities-per-doc: 100
      # 最大关系数量（每个文档）
      max-relations-per-doc: 200
      # 文本分片大小（用于长文档）
      chunk-size: 2000
      # 分片重叠大小
      chunk-overlap: 200

    # 查询配置
    query:
      # 默认查询限制数量
      default-limit: 100
      # 最大查询限制数量
      max-limit: 1000
      # 路径查询最大深度
      max-path-depth: 5
      # 查询超时时间（秒）
      timeout-seconds: 30
      # 是否启用查询缓存
      cache-enabled: true
      # 缓存过期时间（分钟）
      cache-expire-minutes: 60

